{{- if and .Values.tls.clusterIssuer.enabled .Values.tls.clusterIssuer.cloudflare.apiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.clusterIssuer.cloudflare.apiTokenSecretName }}
  namespace: cert-manager
  labels:
    {{- include "bashupload.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-token: {{ .Values.tls.clusterIssuer.cloudflare.apiToken | quote }}
{{- end }}
