apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bashupload.fullname" . }}-config
  namespace: {{ include "bashupload.namespace" . }}
  labels:
    {{- include "bashupload.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.config.port | quote }}
  MAX_UPLOAD_SIZE: {{ .Values.config.maxUploadSize | quote }}
  MAX_AGE: {{ .Values.config.maxAge | quote }}
  MAX_AGE_FOR_MULTIDOWNLOAD: {{ .Values.config.maxAgeForMultidownload | quote }}
  ENABLE_SHORT_URL: {{ .Values.config.enableShortUrl | quote }}
  ALLOW_LIFETIME_OVER_MAX_AGE: {{ .Values.config.allowLifetimeOverMaxAge | quote }}
  SHORT_URL_SERVICE: {{ .Values.config.shortUrlService | quote }}
  NO_CLEANUP: {{ .Values.config.noCleanup | quote }}
