apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bashupload.fullname" . }}-secret
  namespace: {{ include "bashupload.namespace" . }}
  labels:
    {{- include "bashupload.labels" . | nindent 4 }}
type: Opaque
stringData:
  R2_ACCOUNT_ID: {{ .Values.r2.accountId | quote }}
  R2_ACCESS_KEY_ID: {{ .Values.r2.accessKeyId | quote }}
  R2_SECRET_ACCESS_KEY: {{ .Values.r2.secretAccessKey | quote }}
  R2_BUCKET_NAME: {{ .Values.r2.bucketName | quote }}
